# fly.toml app configuration file generated for telis-adopts-web-ui on 2023-12-28T08:42:07-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telis-adopts-web-ui"
primary_region = "scl"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  http_checks = []
  internal_port = 80