import { Colors } from "../../types/commons";

export const CLOUDYSTARS_TEXT_COLOR = "#FFF0E2";
export const CLOUDYSTARS_TITLE_TEXT_COLOR = "#97D4E9";
export const CLOUDYSTARS_BUTTON_COLOR = "#97D4E9";
export const CLOUDYSTARS_BUBBLE_COLOR = "#80B7E4";
export const CLOUDYSTARS_BUBBLE_ICON_COLOR = "#FFF0E2";
export const CLOUDYSTARS_CONTAINER_COLOR = "#97D4E9";
export const CLOUDYSTARS_SECOND_CONTAINER_COLOR = "#FFFFFF";
export const CLOUDYSTARS_BUTTON_SHADOW_COLOR = "#97D4E9";
export const CLOUDYSTARS_BUBBLE_HOME_COLOR = "#97D4E9";
export const CLOUDYSTARS_MENUBAR_COLOR = "#80B7E5";
export const CLOUDYSTARS_MENUBAR_HOVER_COLOR = "#97D4E9";
export const CLOUDYSTARS_TABLE_HEADER_COLOR = "#80B7E5";
export const CLOUDYSTARS_TABLE_HEADER_TEXT_COLOR = "#FFFFFF";
export const CLOUDYSTARS_TABLE_ROW_HOVER_COLOR = "#CDE3F8";
export const CLOUDYSTARS_TABLE_ROW_HOVER_TEXT_COLOR = "#365B78";
export const CLOUDYSTARS_FORM_CONTAINER_COLOR = "#FFFFFF";
export const CLOUDYSTARS_FORM_TITLE_COLOR = "#82B5E2";
export const CLOUDYSTARS_BUTTON_SHADOW_COLOR_2 = "#809FBB";
export const CLOUDYSTARS_FORM_BUTTON_COLOR = "#82B5E2";
export const CLOUDYSTARS_TABLE_TITLE_COLOR = "#9AD2E7";
export const CLOUDYSTARS_MENUBAR_TEXT_COLOR = "#FFFFFF";

export const cloudystarsColors: Colors = {
  text: CLOUDYSTARS_TEXT_COLOR,
  titleText: CLOUDYSTARS_TITLE_TEXT_COLOR,
  button: CLOUDYSTARS_BUTTON_COLOR,
  bubble: CLOUDYSTARS_BUBBLE_COLOR,
  bubbleIcon: CLOUDYSTARS_BUBBLE_ICON_COLOR,
  container: CLOUDYSTARS_CONTAINER_COLOR,
  secondContainer: CLOUDYSTARS_SECOND_CONTAINER_COLOR,
  buttonShadow: CLOUDYSTARS_BUTTON_SHADOW_COLOR,
  bubbleHome: CLOUDYSTARS_BUBBLE_HOME_COLOR,
  menubar: CLOUDYSTARS_MENUBAR_COLOR,
  menubarHover: CLOUDYSTARS_MENUBAR_HOVER_COLOR,
  tableHeader: CLOUDYSTARS_TABLE_HEADER_COLOR,
  tableHeaderText: CLOUDYSTARS_TABLE_HEADER_TEXT_COLOR,
  tableRowHover: CLOUDYSTARS_TABLE_ROW_HOVER_COLOR,
  tableRowHoverText: CLOUDYSTARS_TABLE_ROW_HOVER_TEXT_COLOR,
  formContainer: CLOUDYSTARS_FORM_CONTAINER_COLOR,
  formTitle: CLOUDYSTARS_FORM_TITLE_COLOR,
  buttonShadow2: CLOUDYSTARS_BUTTON_SHADOW_COLOR_2,
  formButton: CLOUDYSTARS_FORM_BUTTON_COLOR,
  tableTitle: CLOUDYSTARS_TABLE_TITLE_COLOR,
  menubarText: CLOUDYSTARS_MENUBAR_TEXT_COLOR,
};
