import { Colors } from "../../types/commons";

export const LANIES_TEXT_COLOR = "#FEF1DF";
export const LANIES_TITLE_TEXT_COLOR = "#F682A0";
export const LANIES_BUTTON_COLOR = "#F682A0";
export const LANIES_BUBBLE_COLOR = "#F682A0";
export const LANIES_BUBBLE_ICON_COLOR = "#FEF1DF";
export const LANIES_CONTAINER_COLOR = "#F682A0";
export const LANIES_SECOND_CONTAINER_COLOR = "#FEF1DF";
export const LANIES_BUTTON_SHADOW_COLOR = "#F682A0";
export const LANIES_BUBBLE_HOME_COLOR = "#F682A0";
export const LANIES_MENUBAR_COLOR = "#F6829F";
export const LANIES_MENUBAR_HOVER_COLOR = "#DB6A86";
export const LANIES_TABLE_HEADER_COLOR = "#F6829F";
export const LANIES_TABLE_HEADER_TEXT_COLOR = "#F6D4D0";
export const LANIES_TABLE_ROW_HOVER_COLOR = "#F9DFC6";
export const LANIES_TABLE_ROW_HOVER_TEXT_COLOR = "#974D5C";
export const LANIES_FORM_CONTAINER_COLOR = "#FEF1DF";
export const LANIES_FORM_TITLE_COLOR = "#F1889E";
export const LANIES_BUTTON_SHADOW_COLOR_2 = "#B75971";
export const LANIES_FORM_BUTTON_COLOR = "#F781A0";
export const LANIES_TABLE_TITLE_COLOR = "#F5839C";
export const LANIES_MENUBAR_TEXT_COLOR = "#FFE7E4";

export const laniesColors: Colors = {
  text: LANIES_TEXT_COLOR,
  titleText: LANIES_TITLE_TEXT_COLOR,
  button: LANIES_BUTTON_COLOR,
  bubble: LANIES_BUBBLE_COLOR,
  bubbleIcon: LANIES_BUBBLE_ICON_COLOR,
  container: LANIES_CONTAINER_COLOR,
  secondContainer: LANIES_SECOND_CONTAINER_COLOR,
  buttonShadow: LANIES_BUTTON_SHADOW_COLOR,
  bubbleHome: LANIES_BUBBLE_HOME_COLOR,
  menubar: LANIES_MENUBAR_COLOR,
  menubarHover: LANIES_MENUBAR_HOVER_COLOR,
  tableHeader: LANIES_TABLE_HEADER_COLOR,
  tableHeaderText: LANIES_TABLE_HEADER_TEXT_COLOR,
  tableRowHover: LANIES_TABLE_ROW_HOVER_COLOR,
  tableRowHoverText: LANIES_TABLE_ROW_HOVER_TEXT_COLOR,
  formContainer: LANIES_FORM_CONTAINER_COLOR,
  formTitle: LANIES_FORM_TITLE_COLOR,
  buttonShadow2: LANIES_BUTTON_SHADOW_COLOR_2,
  formButton: LANIES_FORM_BUTTON_COLOR,
  tableTitle: LANIES_TABLE_TITLE_COLOR,
  menubarText: LANIES_MENUBAR_TEXT_COLOR,
};
