import { Colors } from "../../types/commons";

export const SPECTRALUMEN_TEXT_COLOR = "#F2F5FE";
export const SPECTRALUMEN_TITLE_TEXT_COLOR = "#F682A0";
export const SPECTRALUMEN_BUTTON_COLOR = "#FB77FE";
export const SPECTRALUMEN_BUBBLE_COLOR = "#010000";
export const SPECTRALUMEN_BUBBLE_ICON_COLOR = "#F2F5FE";
export const SPECTRALUMEN_CONTAINER_COLOR = "##FB77FE";
export const SPECTRALUMEN_SECOND_CONTAINER_COLOR = "#F2F5FE";
export const SPECTRALUMEN_BUTTON_SHADOW_COLOR = "#F682A0";
export const SPECTRALUMEN_BUBBLE_HOME_COLOR = "#FB77FE";
export const SPECTRALUMEN_MENUBAR_COLOR = "#000000";
export const SPECTRALUMEN_MENUBAR_HOVER_COLOR = "#FB77FE";
export const SPECTRALUMEN_TABLE_HEADER_COLOR = "#000000";
export const SPECTRALUMEN_TABLE_HEADER_TEXT_COLOR = "#E7E7E7";
export const SPECTRALUMEN_TABLE_ROW_HOVER_COLOR = "#F3C2F7";
export const SPECTRALUMEN_TABLE_ROW_HOVER_TEXT_COLOR = "#000000";
export const SPECTRALUMEN_FORM_CONTAINER_COLOR = "#FFFFFF";
export const SPECTRALUMEN_FORM_TITLE_COLOR = "#FD76FE";
export const SPECTRALUMEN_BUTTON_SHADOW_COLOR_2 = "#7F5180";
export const SPECTRALUMEN_FORM_BUTTON_COLOR = "#FD76FE";
export const SPECTRALUMEN_TABLE_TITLE_COLOR = "#FA75F8";
export const SPECTRALUMEN_MENUBAR_TEXT_COLOR = "#F2F5FE";

export const spectraLumenColors: Colors = {
  text: SPECTRALUMEN_TEXT_COLOR,
  titleText: SPECTRALUMEN_TITLE_TEXT_COLOR,
  button: SPECTRALUMEN_BUTTON_COLOR,
  bubble: SPECTRALUMEN_BUBBLE_COLOR,
  bubbleIcon: SPECTRALUMEN_BUBBLE_ICON_COLOR,
  container: SPECTRALUMEN_CONTAINER_COLOR,
  secondContainer: SPECTRALUMEN_SECOND_CONTAINER_COLOR,
  buttonShadow: SPECTRALUMEN_BUTTON_SHADOW_COLOR,
  bubbleHome: SPECTRALUMEN_BUBBLE_HOME_COLOR,
  menubar: SPECTRALUMEN_MENUBAR_COLOR,
  menubarHover: SPECTRALUMEN_MENUBAR_HOVER_COLOR,
  tableHeader: SPECTRALUMEN_TABLE_HEADER_COLOR,
  tableHeaderText: SPECTRALUMEN_TABLE_HEADER_TEXT_COLOR,
  tableRowHover: SPECTRALUMEN_TABLE_ROW_HOVER_COLOR,
  tableRowHoverText: SPECTRALUMEN_TABLE_ROW_HOVER_TEXT_COLOR,
  formContainer: SPECTRALUMEN_FORM_CONTAINER_COLOR,
  formTitle: SPECTRALUMEN_FORM_TITLE_COLOR,
  buttonShadow2: SPECTRALUMEN_BUTTON_SHADOW_COLOR_2,
  formButton: SPECTRALUMEN_FORM_BUTTON_COLOR,
  tableTitle: SPECTRALUMEN_TABLE_TITLE_COLOR,
  menubarText: SPECTRALUMEN_MENUBAR_TEXT_COLOR,
};
